[package]
name = "system-runtime-primitives"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Primitives of system domain runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { version = "3.4.0", default-features = false, features = ["derive"] }
sp-api = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", branch = "rsub/relay-bench-a" }
sp-core = { version = "7.0.0", default-features = false, git = "https://github.com/subspace/substrate", branch = "rsub/relay-bench-a" }
sp-domains = { version = "0.1.0", default-features = false, path = "../../../crates/sp-domains" }
sp-runtime = { version = "7.0.0", default-features = false, git = "https://github.com/subspace/substrate", branch = "rsub/relay-bench-a" }
sp-std = { version = "5.0.0", default-features = false, git = "https://github.com/subspace/substrate", branch = "rsub/relay-bench-a" }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-domains/std",
	"sp-runtime/std",
	"sp-std/std",
]
